{% set name = "aws-okta-keyman" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 58ba9cb40402ab8bcae2fd8bbcf9966cf9416436cfc84636cadca0e27d5f90a1

build:
  number: 1
  noarch: python
  entry_points:
    - aws_okta_keyman = aws_okta_keyman.__main__:entry_point
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - beautifulsoup4 >=4.4.0
    - boto3 >=1.4.0
    - colorlog >=4.0.0
    - configparser >=3.5.0
    - future >=0.16.0
    - keyring >=18.0.0
    - python >={{ python_min }}
    - pyyaml >=5.0
    - requests >=2.10.0

test:
  imports:
    - aws_okta_keyman
    - aws_okta_keyman.test
  commands:
    - pip check
    - aws_okta_keyman --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nathan-v/aws_okta_keyman
  summary: AWS Okta Keyman
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
