{% set name = "aws-okta-keyman" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 865ba7ef2c5718b5db63007798b96b87b2390a609dca9fe8bd6b99df5c003a75

build:
  number: 0
  noarch: python
  entry_points:
    - aws_okta_keyman = aws_okta_keyman.__main__:entry_point
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - beautifulsoup4 >=4.4.0
    - boto3 >=1.4.0
    - colorlog >=4.0.0
    - configparser >=3.5.0
    - future >=0.16.0
    - keyring >=18.0.0
    - python >=3.6
    - pyyaml >=5.0
    - requests >=2.10.0

test:
  imports:
    - aws_okta_keyman
    - aws_okta_keyman.test
  commands:
    - pip check
    - aws_okta_keyman --help
  requires:
    - pip

about:
  home: https://github.com/nathan-v/aws_okta_keyman
  summary: AWS Okta Keyman
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mariusvniekerk
